# Generated by Django 2.2.16 on 2022-06-01 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220601_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientamount',
            options={'verbose_name': 'Количество ингредиента', 'verbose_name_plural': 'Количество ингредиента'},
        ),
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='Ingredient',
            new_name='ingredient',
        ),
    ]
