# Generated by Django 2.2.16 on 2022-06-01 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220601_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='item_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.Ingredient'),
        ),
    ]
