# Generated by Django 2.2.16 on 2022-06-01 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220601_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientamount',
            name='item_id',
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amount', to='recipes.Ingredient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredientamount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
