# Generated by Django 2.2.16 on 2022-05-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscribe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_auth',
        ),
    ]
